### ISSUE TITLE
A bit more information needed

### ISSUE THREAD

**Issue by rogierlommers** [chr4/enyaq_exporter#1]
Hey, first of all: thanks for your exporter! However, I do have a question: can you elaborate a bit more what all the fields exactly are? I already figured out the following:

- ev_odometer: total kilometers written (integer)
- ev_range: total kilomters left in the battery (integer)
- ev_soc gauge: percentage left in battery (0-100, percents)

But the unknown fields to me are:
- ev_status: integer between 0-3? But what does this say?
- ev_finish_time: most probably the time when charging is finished, but in what format? In other words: what unit should I pick in Grafana?

Example data
```
# HELP ev_finish_time Electric charging finish time
# TYPE ev_finish_time gauge
ev_finish_time 1.702994483e+09
# HELP ev_odometer Electric odometer
# TYPE ev_odometer gauge
ev_odometer 9108
# HELP ev_range Electric vehicle range
# TYPE ev_range gauge
ev_range 57
# HELP ev_soc Electric vehicle state of charge
# TYPE ev_soc gauge
ev_soc 14
# HELP ev_status Electric vehicle status
# TYPE ev_status gauge
ev_status 3
# HELP evcc_http_request_duration_seconds A summary of HTTP request durations
# TYPE evcc_http_request_duration_seconds summary
```

**Comment by chr4** [comment]
Those values are just passed through by [evcc's skoda lib](https://github.com/evcc-io/evcc/blob/master/vehicle/skoda/provider.go).

I believe you are correct with the three metrics you figured out! The other two are defined as follows:

- `ev_finish_time` returns a [UNIX timestamp](https://github.com/chr4/enyaq_exporter/blob/main/main.go#L140), but in scientific notation. I'm actually not sure whether Grafana supports this out of the box (I don't use it currently). But if it doesn't, we might have to export it in a different format. Pull request welcome!

- `ev_status` seems to be [this enum](https://github.com/evcc-io/evcc/blob/master/api/api.go#L34-L43), which is mapped to integers to be compatible with Prometheus [here](https://github.com/chr4/enyaq_exporter/blob/main/main.go#L116-L133). (You're right, some docs here would be super nice. Also, a pull-request is welcome! I can also add this to my TODO, but it will take a while until I'll have time to apply it).

**Comment by rogierlommers** [comment]
here you are: https://github.com/chr4/enyaq_exporter/pull/2

**Comment by chr4** [comment]
Nice! Just merged. Did you find a way to make Grafana interpret the timestamp correctly?

**Comment by rogierlommers** [comment]
> Nice! Just merged. Did you find a way to make Grafana interpret the timestamp correctly?

Hey, no I haven't checked it. I personally don't need this info.
No plans to add it yo my "home dashboard". But when that changes, I will let you know. 👍
